### ISSUE TITLE
Issue with Unobtainium box

### ISSUE THREAD

**Issue by Kinny092** [luisrodrigues154/InfoSec-Learning#2]
Hi Luis.

There is no issue with the guide but I got confused half way and I could not find another way of sending you a direct message.

Looking at the part where it says:

We just need to craft a special payload to pollute prototype to always set canUpload=True on every object

I could not put that as a PUT or POST request in Burp, it would come back as bad request or access denied.

Can you please show the entire burp request?

Also, the part where you had: 
curl -X POST --data '{"auth": {"name": "felamos", "password": "Winter2021"}, "filename" : ""}' -H "Content-Type: application/json" http://unobtainium.htb:31337/todo

This isn't clear enough, I'm not sure where I have to do that, but if I were to send a todo post request without the filename, it would show the same result and Im also not sure if I have to do anything with the JSON script that was extracted.

If you can help me out, that would be much appreciated.

![image](https://user-images.githubusercontent.com/25901267/129055522-548fc4f3-507e-439a-96fe-791d58c8a919.png)

Thanks.

Kin

**Comment by luisrodrigues154** [comment]
Sorry man, i do not check this git stuff regularly !

Did you managed to solve the issue? I hope so !

**Comment by Kinny092** [comment]
no i have not complete the box and i might not have time to do it again soon
